# Max Zhao mlzhao 1466223

all:
	cd problem1/ && \
	g++ main1.cpp problem1.cpp -o main1 && \
	./main1 && \
	cd -

	cd problem2/ && \
	g++ main2.cpp problem2.cpp -o main2 && \
	./main2 && \
	cd -

	cd problem3/ && \
	g++ main3.cpp problem3.cpp -o main3 && \
	./main3